baseURL: 'https://ymlai87416.github.io'
defaultContentLanguage: zh
theme: LoveIt
#themesDir: ../..
title: Tom personal site
enableRobotsTXT: true
enableGitInfo: false
enableEmoji: true
languages:
  zh:
    weight: 1
    languageCode: zh
    languageName: 中文
    hasCJKLanguage: true
    paginate: 12
    googleAnalytics: ''
    copyright: >-
      This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    menu:
      main:
        - identifier: about
          pre: ''
          post: ''
          name: About
          url: /about/
          title: ''
          weight: 1
        - identifier: blog
          pre: ''
          post: ''
          name: Blog
          url: /blog/
          title: ''
          weight: 2
        - identifier: cheatsheet
          pre: ''
          post: ''
          name: Cheatsheet
          url: /cheatsheet/
          title: ''
          weight: 3
        - identifier: tools
          pre: ''
          post: ''
          name: Tools
          url: /tools/
          title: ''
          weight: 4
        - identifier: link
          pre: ''
          post: ''
          name: Link
          url: /link/
          title: ''
          weight: 5
    params:
      description: Tom personal web site
      keywords:
        - ymlai87416
        - Lai Yiu Ming
      app:
        title: Tom personal web site
        noFavicon: false
        svgFavicon: ''
        themeColor: '#ffffff'
        iconColor: '#5bbad5'
        tileColor: '#da532c'
      search:
        enable: false
        type: algolia
        contentLength: 4000
        placeholder: ''
        maxResultLength: 10
        snippetLength: 30
        highlightTag: em
        absoluteURL: false
        algolia:
          index: index.en
          appID: PASDMWALPK
          searchKey: b42948e51daaa93df92381c8e2ac0f93
      home:
        rss: 10
        profile:
          enable: true
          gravatarEmail: ''
          avatarURL: /images/avatar.jpg
          title: ''
          subtitle: 'Tom personl web site'
          typeit: true
          social: true
          disclaimer: ''
        posts:
          enable: true
          paginate: 6
      social:
        GitHub: ymlai87416
        Linkedin: lai-yiu-ming-a586b83b
        Twitter: ymlai87416
        Instagram: ymlai87416
        Facebook: ''
        Telegram: ''
        Medium: ''
        Gitlab: ''
        Youtubelegacy: ''
        Youtubecustom: ''
        Youtubechannel: 'UCyOM8i3ueCkTMtuONeXG09Q'
        Tumblr: ''
        Quora: ''
        Keybase: ''
        Pinterest: ''
        Reddit: ''
        Codepen: ''
        FreeCodeCamp: ''
        Bitbucket: ''
        Stackoverflow: ''
        Weibo: ''
        Odnoklassniki: ''
        VK: ''
        Flickr: ''
        Xing: ''
        Snapchat: ''
        Soundcloud: ''
        Spotify: ''
        Bandcamp: ''
        Paypal: ''
        Fivehundredpx: ''
        Mix: ''
        Goodreads: ''
        Lastfm: ''
        Foursquare: ''
        Hackernews: ''
        Kickstarter: ''
        Patreon: ''
        Steam: ''
        Twitch: ''
        Strava: ''
        Skype: ''
        Whatsapp: ''
        Zhihu: ''
        Douban: ''
        Angellist: ''
        Slidershare: ''
        Jsfiddle: ''
        Deviantart: ''
        Behance: ''
        Dribbble: ''
        Wordpress: https://www.ymlai87416.com
        Vine: ''
        Googlescholar: ''
        Researchgate: ''
        Thingiverse: ''
        Devto: ''
        Gitea: ''
        XMPP: ''
        Matrix: ''
        Bilibili: ''
        Email: ymlai87416@gmail.com
        RSS: true
        Mastodon: ''
  
params:
  version: 0.2.X
  defaultTheme: auto
  gitRepo: 'https://github.com/ymlai87416/ymlai87416.github.io'
  fingerprint: ''
  dateFormat: '2006-01-02'
  images:
    - /logo.png
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ''
      name: Tom personal site
      pre: ''
      post: ''
      typeit: false
  footer:
    enable: true
    custom: ''
    hugo: true
    copyright: true
    author: true
    since: 2016
    icp: ''
    license: >-
      <a rel="license external nofollow noopener noreffer"
      href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC
      BY-NC 4.0</a>
  section:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  list:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    twemoji: false
    lightgallery: false
    ruby: true
    fraction: true
    fontawesome: true
    linkToMarkdown: true
    rssFullText: false
    toc:
      enable: true
      keepStatic: false
      auto: true
    code:
      copy: true
      maxShownLines: 100
    math:
      enable: false
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      copyTex: true
      mhchem: true
    mapbox:
      accessToken: >-
        pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ
      lightStyle: 'mapbox://styles/mapbox/light-v10?optimize=true'
      darkStyle: 'mapbox://styles/mapbox/dark-v10?optimize=true'
      navigation: true
      geolocate: true
      scale: true
      fullscreen: true
    share:
      enable: false
      Twitter: true
      Facebook: true
      Linkedin: false
      Whatsapp: false
      Pinterest: false
      Tumblr: false
      HackerNews: false
      Reddit: false
      VK: false
      Buffer: false
      Xing: false
      Line: true
      Instapaper: false
      Pocket: false
      Digg: false
      Stumbleupon: false
      Flipboard: false
      Weibo: false
      Renren: false
      Myspace: false
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: false
      disqus:
        enable: false
        shortname: ''
      gitalk:
        enable: false
        owner: ''
        repo: ''
        clientId: ''
        clientSecret: ''
      valine:
        enable: true
        appId: QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI
        appKey: WBmoGyJtbqUswvfLh6L8iEBr
        placeholder: ''
        avatar: mp
        meta: ''
        pageSize: 10
        lang: ''
        visitor: true
        recordIP: true
        highlight: true
        enableQQ: false
        serverURLs: 'https://leancloud.hugoloveit.com'
        emoji: ''
      facebook:
        enable: false
        width: 100%
        numPosts: 10
        appId: ''
        languageCode: ''
      telegram:
        enable: false
        siteID: ''
        limit: 5
        height: ''
        color: ''
        colorful: true
        dislikes: false
        outlined: false
      commento:
        enable: false
      utterances:
        enable: false
        repo: ''
        issueTerm: pathname
        label: ''
        lightTheme: github-light
        darkTheme: github-dark
    library:
      css: {}
      js: {}
    seo:
      images: []
      publisher:
        name: Tom
        logoUrl: /images/avatar.jpg
  typeit:
    speed: 100
    cursorSpeed: 1000
    cursorChar: '|'
    duration: -1
  verification:
    google: ''
    bing: ''
    yandex: ''
    pinterest: ''
    baidu: ''
  seo:
    image: /images/Apple-Devices-Preview.png
    thumbnailUrl: /images/screenshot.png
  analytics:
    enable: false
    google:
      id: ''
      anonymizeIP: true
    fathom:
      id: ''
      server: ''
  cookieconsent:
    enable: false
    content:
      message: ''
      dismiss: ''
      link: ''
  cdn:
    data: jsdelivr.yml
  compatibility:
    polyfill: false
    objectFit: false
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
author:
  name: Lai Yiu Ming, Tom
  email: 'ymlai87416@gmail.com'
  link: ''
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: ':filename'
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML

