name: Build site

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # extended: true

    - name: Build
      run: 

    - name: Copy english
      run: cp -R englishVocab mysite/public

    - name: Copy algorithm
      run: cp -R algoSummary mysite/public

    - name: Copy putonghua
      run: cp -R putonghua mysite/public

    - name: Copy mytool
      run: cp -R mytool mysite/public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mysite/public
    