name: Build site

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify -s mysite

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      
      - uses: actions/upload-artifact@v2
        with:
          name: upload-english
          path: englishVocab

     - uses: actions/upload-artifact@v2
        with:
          name: upload-putonghua
          path: putonghua

      - uses: actions/upload-artifact@v2
        with:
          name: upload-mytool
          path: mytool

      - uses: actions/upload-artifact@v2
        with:
          name: upload-algo
          path: algoSummary
